// src/components/Dashboard/Info/Info.tsx
import {InfosData} from "../../../interface";
import React from "react";
import classesCSS from "./style.module.scss";

export function InfoGet(props: { info: InfosData }): any {
    const {info} = props;

    return (
        <div className={classesCSS.contract}>
            <br/>
            <table aria-colspan={2}>
                <thead>
                <tr>
                    <th colSpan={2}>IP</th>
                </tr>
                <tr>
                    <th>IP Version</th>
                    <th>Address</th>
                </tr>
                {
                    info.v4?.map((v4) =>
                        <tr>
                            <td>IPv4</td>
                            <td>{v4}</td>
                        </tr>
                    )
                }
                {
                    info.v6?.map((v6) =>
                        <tr>
                            <td>IPv6</td>
                            <td>{v6}</td>
                        </tr>
                    )
                }
                </thead>
            </table>
            <br/>
            <table aria-colspan={2}>
                <thead>
                <tr>
                    <th colSpan={2}>内容</th>
                </tr>
                <tr>
                    <th>サービス種別</th>
                    <td>{info.service}</td>
                </tr>
                <tr>
                    <th>利用料金</th>
                    <td>{info.fee}</td>
                </tr>
                <tr>
                    <th>当団体からのIPアドレスの割当</th>
                    {
                        info.assign &&
                        <td>当団体から割当</td>
                    }
                    {
                        !info.assign &&
                        <td>貴団体から割当</td>
                    }
                </tr>
                </thead>
            </table>
            <br/>
            <table className={classesCSS.contract}>
                <thead>
                <tr>
                    <th colSpan={3}>接続情報</th>
                </tr>
                <tr>
                    <th>接続方式</th>
                    <td colSpan={2}>{info.service}</td>
                </tr>
                <tr>
                    <th>接続NOC</th>
                    <td colSpan={2}>{info.noc}</td>
                </tr>
                <tr>
                    <th>トンネル終端アドレス（貴団体側）</th>
                    <td colSpan={2}>{info.term_ip}</td>
                </tr>
                <tr>
                    <th>トンネル終端アドレス（HomeNOC側）</th>
                    <td colSpan={2}>{info.noc_ip}</td>
                </tr>
                <tr>
                    <th colSpan={3}>当団体との間の境界アドレス</th>
                </tr>
                <tr>
                    <th/>
                    <th>IPv4アドレス</th>
                    <th>IPv6アドレス</th>
                </tr>
                <tr>
                    <th>HomeNOC側</th>
                    <td>{info.link_v4_our}</td>
                    <td>{info.link_v6_our}</td>
                </tr>
                <tr>
                    <th>貴団体側</th>
                    <td>{info.link_v4_your}</td>
                    <td>{info.link_v6_your}</td>
                </tr>
                </thead>
            </table>
        </div>
    )
}

// src/app/dashboard/info/info.component.ts
import {Component, OnInit} from '@angular/core';
import {InfoService} from '../../service/info.service';
import {Router} from '@angular/router';

@Component({
  selector: 'app-data',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.scss']
})
export class InfoComponent implements OnInit {


  constructor(
    private infoService: InfoService,
  ) {
  }

  public info = [];

  ngOnInit() {
    this.infoService.get().then(response => {
      console.log('---response---');
      console.log(response);
      this.info = response.info;
    });
  }
}

<div class="main">
  <ng-container *ngIf="result">
    <ng-container *ngFor="let d of info">
      <mat-card class="card">
        <mat-card-header>
          <mat-card-title>{{d.service_id}}</mat-card-title>
          <mat-card-subtitle>AS{{d.asn}}</mat-card-subtitle>
          <mat-card-subtitle></mat-card-subtitle>
        </mat-card-header>
        <mat-card-content>

          <br><br>
          <table border="1">
            <tr>
              <th>IPv4</th>
            </tr>
            <tr *ngFor="let ip of d.v4">
              <td>{{ ip }}</td>
            </tr>
          </table>
          <br>
          <table border="1">
            <tr>
              <th>IPv6</th>
            </tr>
            <tr *ngFor="let ip of d.v6">
              <td>{{ ip }}</td>
            </tr>
          </table>
          <br>
          <table>
            <tr>
              <th colspan="2">契約内容</th>
            </tr>
            <tr>
              <th>サービス種別</th>
              <td>{{d.service}}</td>
            </tr>
            <tr>
              <th>ユーザID</th>
              <td>{{d.user_id}}</td>
            </tr>
            <tr>
              <th>利用料金</th>
              <td>{{d.fee}}</td>
            </tr>
            <tr>
              <th>当団体からのIPアドレスの割当</th>
              <td>{{d.assign}}</td>
            </tr>
          </table>
          <br>
          <table>
            <tr>
              <th colspan="3">接続情報</th>
            </tr>
            <tr>
              <th>接続方式</th>
              <td colspan="2">{{d.service}}</td>
            </tr>
            <tr>
              <th>接続NOC</th>
              <td colspan="2">{{d.noc}}</td>
            </tr>
            <tr>
              <th>トンネル終端アドレス（貴団体側）</th>
              <td colspan="2">{{d.term_ip}}</td>
            </tr>
            <tr>
              <th>トンネル終端アドレス（当団体側）</th>
              <td colspan="2">{{d.noc_ip}}</td>
            </tr>
            <tr>
              <th colspan="3">当団体との間の境界アドレス</th>
            </tr>
            <tr>
              <th></th>
              <th>IPv4アドレス</th>
              <th>IPv6アドレス</th>
            </tr>
            <tr>
              <th>当団体側</th>
              <td>{{d.link_v4_our}}</td>
              <td>{{d.link_v6_our}}</td>
            </tr>
            <tr>
              <th>貴団体側</th>
              <td>{{d.link_v4_your}}</td>
              <td>{{d.link_v6_your}}</td>
            </tr>
          </table>
          <br><br>
          <p><b>本ページは電気通信事業法 第26条2（書面の交付義務）に基づく書面となります。</b></p>
          <p><b>なお、郵送での書面交付をご希望頂いた方は、お送りします書面が正式書面となり、本画面の表示は参考情報となります。</b></p>
        </mat-card-content>
      </mat-card>
    </ng-container>
  </ng-container>
  <ng-container *ngIf="!result">
    <h1>現在、開通している接続がありません。</h1>
    <br>
    <h2>内容</h2>
    <p><b>{{errorResult}}</b></p>
    <br>
    <br>
    <br>
    <h3>レスポンス情報</h3>
    <p>{{errorDetailJSON}}</p>
  </ng-container>
</div>
